# Generated by Django 4.0.2 on 2022-02-16 21:08

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Card',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('card_number', models.CharField(max_length=255)),
                ('register_date', models.DateTimeField(auto_now=True)),
                ('expiration_date', models.CharField(max_length=255)),
                ('ccv', models.CharField(max_length=255)),
                ('account_number', models.CharField(max_length=50, unique=True)),
                ('pin', models.CharField(max_length=255)),
                ('salt', models.CharField(max_length=255)),
                ('last_digits', models.CharField(max_length=4)),
                ('is_active', models.BooleanField(default=True)),
            ],
        ),
        migrations.CreateModel(
            name='Operation',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('datetime', models.DateTimeField(auto_now=True)),
                ('description', models.CharField(max_length=80)),
                ('amount', models.DecimalField(decimal_places=2, max_digits=10)),
                ('egreso', models.BooleanField()),
                ('receiving_card', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='operation_receiver', to='bank_accounts_api.card')),
                ('sender_card', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='operation_sender', to='bank_accounts_api.card')),
            ],
        ),
    ]
