# Generated by Django 4.0.2 on 2022-02-12 23:26

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Card',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('card_number', models.CharField(max_length=255)),
                ('register_date', models.DateTimeField(auto_now=True)),
                ('expiration_date', models.CharField(max_length=255)),
                ('ccv', models.CharField(max_length=255)),
                ('account_number', models.BigIntegerField(unique=True)),
                ('pin', models.CharField(max_length=255)),
                ('salt', models.CharField(max_length=255)),
                ('last_digits', models.IntegerField()),
                ('is_active', models.BooleanField(default=True)),
            ],
        ),
        migrations.CreateModel(
            name='Operations',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('datetime', models.DateTimeField()),
                ('description', models.CharField(max_length=80)),
                ('amount', models.DecimalField(decimal_places=2, max_digits=10)),
                ('type', models.CharField(choices=[('ingreso', 'ingreso'), ('egreso', 'egreso')], max_length=12)),
                ('destination_account', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='operation_destination', to='bank_accounts_api.card')),
                ('origin_account', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='operation_origin', to='bank_accounts_api.card')),
            ],
        ),
    ]
