# Generated by Django 4.0.2 on 2022-02-11 14:34

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('bank_accounts_api', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='card',
            name='register_date',
            field=models.DateTimeField(auto_now=True),
        ),
        migrations.AlterField(
            model_name='operations',
            name='destination_account',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='operation_destination', to='bank_accounts_api.card'),
        ),
        migrations.AlterField(
            model_name='operations',
            name='origin_account',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='operation_origin', to='bank_accounts_api.card'),
        ),
    ]
