# Generated by Django 4.0.2 on 2022-02-16 21:13

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('bank_accounts_api', '0002_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='operation',
            name='egreso',
        ),
    ]
