# Generated by Django 4.0.2 on 2022-02-13 00:07

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('bank_accounts_api', '0002_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='card',
            name='account_number',
            field=models.CharField(max_length=50, unique=True),
        ),
    ]
