# Generated by Django 4.0.2 on 2022-02-16 22:11

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('bank_accounts_api', '0003_remove_operation_egreso'),
    ]

    operations = [
        migrations.AddField(
            model_name='operation',
            name='egreso',
            field=models.BooleanField(default=False),
            preserve_default=False,
        ),
    ]
