# Generated by Django 4.0.2 on 2022-02-14 22:53

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('bank_accounts_api', '0004_alter_card_client'),
    ]

    operations = [
        migrations.AlterField(
            model_name='card',
            name='last_digits',
            field=models.CharField(max_length=4),
        ),
    ]
